export const FLASH_MESSAGE = {
  SUCCESS: 'success',
  ERROR: 'error',
  UNESPECTED_ERROR: 'Ocorreu um erro inesperado, por-favor tente mais tarde',
  SERVER_ERROR_500: 'Ocorreu um erro no servidor, por-favor tente mais tarde',
  NOTAUTHORIZED: 'Não tem autorização para realizar essa operação',
  NO_TOKEN: 'Nenhum token encontrado, por-favor tente novamente',
  WARNING: 'warning',
  INFO: 'info',
  WRONGE: 'Ocorreu um erro, por-favor tente novamente',
  WELLCOME: 'Bem vindo',
  WRONGE_CREDENTIALS: 'Credenciais incorretas, por-favor tente novamente',
  CREATED: 'Entidade cadastrada',
  NOT_CREATED: 'Ocorreu um ao cadastra',
  UPDATED: 'Informação atualizada',
  NOT_UPDATED: 'Ocorreu um erro ao atualizar',
  DELETED: 'Endidate eliminada',
  NOT_DELETED: 'Ocorreu um erro ao excluir',
  ASSIGN_FACULTIES: ' Atribuir professores ao curso com sucesso',
  ASSIGN_FACULTIES_ERROR: 'Ocorreu um erro ao atribuir professores ao curso',
  USER_NOT_DELETED: 'Útilizador não eliminado',
};
