export const FLASH_MESSAGE = {
  SUCCESS: 'success',
  ERROR: 'error',
  UNESPECTED_ERROR: 'Ocorreu um erro inesperado, por-favor tente mais tarde',
  SERVER_ERROR_500: 'Ocorreu um erro no servidor, por-favor tente mais tarde',
  NOTAUTHORIZED: 'Não autorização para realizar essa operação',
  NO_TOKEN: 'Nenhum token encontrado, por-favor tente novamente',
  WARNING: 'warning',
  INFO: 'info',
  WRONGE: 'Ocorreu um erro, por-favor tente novamente',
  WELLCOME: 'Bem vindo',
  WRONGE_CREDENTIALS: 'Credenciais incorretas, por-favor tente novamente',
  ASSIGN_FACULTIES: ' Atribuir professores ao curso com sucesso',
  ASSIGN_FACULTIES_ERROR: 'Ocorreu um erro ao atribuir professores ao curso',
  USER_CREATED: 'Útilizador criado com sucesso',
  USER_NOT_CREATED: 'Utilizador não criado',
  USER_UPDATED: 'Útilizador actualizado com sucesso',
  USER_NOT_UPDATED: 'Útilizador não actualizado',
  USER_DELETED: 'Útilizador eliminado com sucesso',
  USER_NOT_DELETED: 'Útilizador não eliminado',
  FACULTY_CREATED: 'Professor criado com sucesso',
  FACULTY_NOT_CREATED: 'Professor não criado',
  FACULTY_UPDATED: 'Professor actualizado com sucesso',
  FACULTY_NOT_UPDATED: 'Professor não actualizado',
  FACULTY_DELETED: 'Professor eliminado com sucesso',
  FACULTY_NOT_DELETED: 'Professor não eliminado',
  ACADEMIC_FACULTY_CREATED: 'Unidade acadêmica criada com sucesso',
  ACADEMIC_FACULTY_NOT_CREATED: 'Ocorreu um erro ao cria unidade acadêmica',
  ACADEMIC_FACULTY_UPDATED: 'Unidade acadêmica actualizado com sucesso',
  ACADEMIC_FACULTY_NOT_UPDATED:
    'Ocorreu um erro ao atualizar a unidade acadêmica',
  ACADEMIC_FACULTY_DELETED: 'Unidade acadêmica eliminado com sucesso',
  ACADEMIC_FACULTY_NOT_DELETED: 'Ocorreu um erro ao eliminar unidade acadêmica',
  BUILDING_CREATED: 'Edificio criado com sucesso',
  BUILDING_NOT_CREATED: 'Edificio nao criado',
  BUILDING_UPDATED: 'Edificio actualizado com sucesso',
  BUILDING_NOT_UPDATED: 'Edificio nao actualizado',
  BUILDING_DELETED: 'Edificio eliminado com sucesso',
  BUILDING_NOT_DELETED: 'Edificio nao eliminado',
  ROOM_CREATED: 'Sala criado com sucesso',
  ROOM_NOT_CREATED: 'Sala nao criado',
  ROOM_UPDATED: 'Sala actualizado com sucesso',
  ROOM_NOT_UPDATED: 'Sala nao actualizado',
  ROOM_DELETED: 'Sala eliminado com sucesso',
  ROOM_NOT_DELETED: 'Sala nao eliminado',
  COURSE_CREATED: 'Curso criado com sucesso',
  COURSE_NOT_CREATED: 'Curso não criado',
  COURSE_UPDATED: 'Curso actualizado com sucesso',
  COURSE_NOT_UPDATED: 'Curso não actualizado',
  COURSE_DELETED: 'Curso eliminado com sucesso',
  COURSE_NOT_DELETED: 'Curso não eliminado',
  COURSE_PRICE_CREATED: 'Preço criado com sucesso',
  COURSE_PRICE_NOT_CREATED: 'Ocorreu um erro ao criar a Preço',
  COURSE_PRICE_UPDATED: 'Preço actualizado com sucesso',
  COURSE_PRICE_NOT_UPDATED: 'Ocorreu um erro ao atualizar o Preço',
  COURSE_PRICE_DELETED: 'Curso eliminado com sucesso',
  COURSE_PRICE_NOT_DELETED: 'Ocorreu um erro ao eliminar a Preço',
  DETEPARTMENT_CREATED: 'Departamento criado com sucesso',
  DEPARTMENT_NOT_CREATED: 'Departamento nao criado',
  DEPARTMENT_UPDATED: 'Departamento actualizado com sucesso',
  DEPARTMENT_NOT_UPDATED: 'Departamento nao actualizado',
  DEPARTMENT_DELETED: 'Departamento eliminado com sucesso',
  DEPARTMENT_NOT_DELETED: 'Departamento nao eliminado',
  DISCIPLINE_CREATED: 'Disciplina criado com sucesso',
  DISCIPLINE_NOT_CREATED: 'Disciplina nao criado',
  DISCIPLINE_UPDATED: 'Disciplina actualizado com sucesso',
  DISCIPLINE_NOT_UPDATED: 'Ocorreu um erro ao atualizar a disciplina',
  DISCIPLINE_DELETED: 'Disciplina eliminado com sucesso',
  DISCIPLINE_NOT_DELETED: 'Ocorreu um erro ao eliminar a disciplina',
  EXAM_CREATED: 'Exame criado com sucesso',
  EXAM_NOT_CREATED: 'Exame nao criado',
  EXAM_UPDATED: 'Exame actualizado com sucesso',
  EXAM_NOT_UPDATED: 'Exame nao actualizado',
  EXAM_DELETED: 'Exame eliminado com sucesso',
  EXAM_NOT_DELETED: 'Exame nao eliminado',
  ADMITION_EXAME_DELETED: 'Exame de admição eliminado com sucesso',
  ADMITION_EXAME_NOT_DELETED: 'Ocorreu um erro ao eliminar o exame de admição',
  ADMITION_EXAME_CREATED: 'Exame de admição criado com sucesso',
  ADMITION_EXAME_NOT_CREATED: 'Ocorreu um erro ao criar o exame de admição',
  ADMITION_EXAME_UPDATED: 'Exame de admição actualizado com sucesso',
  ADMITION_EXAME_NOT_UPDATED: 'Ocorreu um erro ao atualizar o exame de admição',
  SEMESTER_CREATED: 'Semestre criado',
  SEMESTER_NOT_CREATED: 'Semestre não criado',
  SEMESTER_UPDATED: 'Semestre atualizado',
  SEMESTER_NOT_UPDATED: 'Semestre não atualizado',
  SEMESTER_DELETED: 'Semestre eliminado',
  SEMESTER_NOT_DELETED: 'Semestre não eliminado',
};
