export const FLASH_MESSAGE = {
  SUCCESS: 'success',
  ERROR: 'error',
  UNESPECTED_ERROR: 'Ocorreu um erro inesperado, por-favor tente mais tarde',
  SERVER_ERROR_500: 'Ocorreu um erro no servidor, por-favor tente mais tarde',
  NOTAUTHORIZED: 'Não autorização para realizar essa operação',
  NO_TOKEN: 'Nenhum token encontrado, por-favor tente novamente',
  WARNING: 'warning',
  INFO: 'info',
  WRONGE: 'Ocorreu um erro, por-favor tente novamente',
  WELLCOME: 'Bem vindo',
  WRONGE_CREDENTIALS: 'Credenciais incorretas, por-favor tente novamente',
  USER_CREATED: 'Útilizador criado com sucesso',
  USER_NOT_CREATED: 'Utilizador não criado',
  USER_UPDATED: 'Útilizador actualizado com sucesso',
  USER_NOT_UPDATED: 'Útilizador não actualizado',
  USER_DELETED: 'Útilizador eliminado com sucesso',
  USER_NOT_DELETED: 'Útilizador não eliminado',
  FACULTY_CREATED: 'Professor criado com sucesso',
  FACULTY_NOT_CREATED: 'Professor não criado',
  FACULTY_UPDATED: 'Professor actualizado com sucesso',
  FACULTY_NOT_UPDATED: 'Professor não actualizado',
  FACULTY_DELETED: 'Professor eliminado com sucesso',
  FACULTY_NOT_DELETED: 'Professor não eliminado',
  COURSE_CREATED: 'Curso criado com sucesso',
  COURSE_NOT_CREATED: 'Curso não criado',
  COURSE_UPDATED: 'Curso actualizado com sucesso',
  COURSE_NOT_UPDATED: 'Curso não actualizado',
  COURSE_DELETED: 'Curso eliminado com sucesso',
  COURSE_NOT_DELETED: 'Curso não eliminado',
  DETEPARTMENT_CREATED: 'Departamento criado com sucesso',
  DEPARTMENT_NOT_CREATED: 'Departamento nao criado',
  DEPARTMENT_UPDATED: 'Departamento actualizado com sucesso',
  DEPARTMENT_NOT_UPDATED: 'Departamento nao actualizado',
  DEPARTMENT_DELETED: 'Departamento eliminado com sucesso',
  DEPARTMENT_NOT_DELETED: 'Departamento nao eliminado',
  EXAM_CREATED: 'Exame criado com sucesso',
  EXAM_NOT_CREATED: 'Exame nao criado',
  EXAM_UPDATED: 'Exame actualizado com sucesso',
  EXAM_NOT_UPDATED: 'Exame nao actualizado',
  EXAM_DELETED: 'Exame eliminado com sucesso',
  EXAM_NOT_DELETED: 'Exame nao eliminado',
  SEMESTER_CREATED: 'Semestre criado',
  SEMESTER_NOT_CREATED: 'Semestre não criado',
  SEMESTER_UPDATED: 'Semestre atualizado',
  SEMESTER_NOT_UPDATED: 'Semestre não atualizado',
  SEMESTER_DELETED: 'Semestre eliminado',
  SEMESTER_NOT_DELETED: 'Semestre não eliminado',
};
