import React from 'react';
import {
  Book,
  Building,
  Home,
  BookCheck,
  BookType,
  Currency,
  BookKey,
  Building2Icon,
  AlignHorizontalJustifyEndIcon,
  UserPlus2,
  Receipt,
  BookCopy,
  Archive,
  Rows4,
  BookMarked,
} from 'lucide-react';

export const LINKS_BY_ROLE = {
  super_admin: [
    {
      href: `/crm/admin`,
      label: 'Admin Dashboard',
      icon: React.createElement(Home),
      section: 'general',
      children: [],
    },
    {
      href: `/crm/admin/academic-faculty`,
      label: 'Unidade Acadêmica',
      icon: React.createElement(Book),
      section: 'academic',
      children: [],
    },
    {
      href: `/crm/admin/departments`,
      label: 'Departamentos Acadêmico',
      icon: React.createElement(Building),
      section: 'academic',
      children: [],
    },
    {
      href: `#`,
      label: 'Exames',
      icon: React.createElement(Book),
      section: 'exame',
      children: [
        {
          href: '/crm/admin/exames/admition',
          label: 'Exame de Acesso',
        },
        {
          href: '/crm/admin/exames/retake',
          label: 'Exame de Recurso',
        },
        {
          href: '/crm/admin/exames/special',
          label: 'Exame Special',
        },
      ],
    },
    {
      href: `/crm/admin/academic-semester`,
      label: 'Semestre Acadêmico',
      icon: React.createElement(BookCheck),
      section: 'academic',
      children: [],
    },
    {
      href: `/crm/admin/semester-registration`,
      label: 'Registro Semestral',
      icon: React.createElement(BookCopy),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/courses`,
      label: 'Cursos Acadêmico',
      icon: React.createElement(BookType),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/price-managemente`,
      label: 'Preços Acadêmico',
      icon: React.createElement(Currency),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/disciplines`,
      label: 'Deciplinas Acadêmico',
      icon: React.createElement(BookKey),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/offered-course`,
      label: 'Cadeiras Semestrais',
      icon: React.createElement(Archive),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/course-section`,
      label: 'Turmas',
      icon: React.createElement(Rows4),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/class-schedule`,
      label: 'Horarios',
      icon: React.createElement(BookMarked),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/buildings`,
      label: 'Edificios',
      icon: React.createElement(Building2Icon),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/rooms`,
      label: 'Salas',
      icon: React.createElement(AlignHorizontalJustifyEndIcon),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/faculty`,
      label: 'Professores',
      icon: React.createElement(UserPlus2),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/student`,
      label: 'Estudantes',
      icon: React.createElement(UserPlus2),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/finance`,
      label: 'Orçamentos',
      icon: React.createElement(Receipt),
      section: 'finance',
      children: [],
    },
  ],
  admin: [
    {
      href: `/crm/admin`,
      label: 'Admin Dashboard',
      icon: React.createElement(Home),
      section: 'general',
      children: [],
    },
    {
      href: `/crm/admin/academic-faculty`,
      label: 'Unidade Acadêmica',
      icon: React.createElement(Book),
      section: 'academic',
      children: [],
    },
    {
      href: `/crm/admin/departments`,
      label: 'Departamentos Acadêmico',
      icon: React.createElement(Building),
      section: 'academic',
      children: [],
    },
    {
      href: `/crm/admin/admition-exames`,
      label: 'Exames de admisão',
      icon: React.createElement(Book),
      section: 'exame',
      children: [],
    },
    {
      href: `/crm/admin/academic-semester`,
      label: 'Semestre Acadêmico',
      icon: React.createElement(BookCheck),
      section: 'academic',
      children: [],
    },
    {
      href: `/crm/admin/semester-registration`,
      label: 'Registro Semestral',
      icon: React.createElement(BookCopy),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/courses`,
      label: 'Cursos Acadêmico',
      icon: React.createElement(BookType),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/price-managemente`,
      label: 'Preços Acadêmico',
      icon: React.createElement(Currency),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/disciplines`,
      label: 'Deciplinas Acadêmico',
      icon: React.createElement(BookKey),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/offered-course`,
      label: 'Cadeiras Semestrais',
      icon: React.createElement(Archive),
      section: 'course',
      children: [],
    },
    {
      href: `/crm/admin/course-section`,
      label: 'Turmas',
      icon: React.createElement(Rows4),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/class-schedule`,
      label: 'Horarios',
      icon: React.createElement(BookMarked),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/buildings`,
      label: 'Edificios',
      icon: React.createElement(Building2Icon),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/rooms`,
      label: 'Salas',
      icon: React.createElement(AlignHorizontalJustifyEndIcon),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/faculty`,
      label: 'Professores',
      icon: React.createElement(UserPlus2),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/admin/student`,
      label: 'Estudantes',
      icon: React.createElement(UserPlus2),
      section: 'entitys',
      children: [],
    },
    {
      href: `/crm/finance`,
      label: 'Orçamentos',
      icon: React.createElement(Receipt),
      section: 'finance',
      children: [],
    },
  ],
};
export const SECTION_LABELS: Record<string, string> = {
  general: 'Geral',
  academic: 'Acadêmico',
  course: 'Cursos & Matrículas',
  entitys: 'Recursos',
  exame: 'Avaliações',
  finance: 'Financeiro',
};

export const SECTION_ORDER = [
  'general',
  'academic',
  'course',
  'entitys',
  'exame',
  'finance',
];
