export const ROUTES = {
  DASHBOARD: '/crm',
  ADMIN_DASHBORD: '/crm/admin',
  UNAUTHORIZED: '/unauthorized',
  LOGIN: `${process.env.NEXT_PUBLIC_BASE_URL}/auth/login`,
  RECOVER_PASSWORD: `${process.env.NEXT_PUBLIC_BASE_URL}/auth/apanel/recover-password`,
  RESET_PASSWORD: `${process.env.NEXT_PUBLIC_BASE_URL}/auth/apanel/reset-password`,
  CALENDAR: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/management/calendar`,
  ACCOUNT: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/general-secretary`,
  SECRETARY: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/general-secretary`,
  USERS: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/users`,
  AUDI_LOGS: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/activitys`,
  RULES_SETTINGS: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/university`,
  SETTINGS: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/settings`,
  BANK_ACCOUNTS: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/finance/accounts`,
  SUPORTE: `${process.env.NEXT_PUBLIC_BASE_URL}/crm/admin/suporte`,
};
