const {
  NEXT_APP_SITE_NAME,
  NEXT_PUBLIC_BASE_URL,
  API_BASE_URL,
  API_ASSETS_URL,
} = process.env;

export default {
  APP_NAME: NEXT_APP_SITE_NAME,
  PUBLIC_URL: NEXT_PUBLIC_BASE_URL,
  API_URL: API_BASE_URL,
  API_ASSETS_URL,
};
