const {
  NEXT_APP_SITE_NAME,
  NEXT_PUBLIC_BASE_URL,
  API_BASE_URL,
  API_ASSETS_URL,
  NEXTAUTH_SECRET,
  NEXTAUTH_URL,
  NEXT_PUBLIC_TIME_OUT_MS,
  NEXT_PUBLIC_TIME_OUT_CHECK_MS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
} = process.env;

export default {
  APP_NAME: NEXT_APP_SITE_NAME,
  PUBLIC_URL: NEXT_PUBLIC_BASE_URL,
  API_URL: API_BASE_URL,
  API_ASSETS_URL,
  NEXTAUTH_SECRET,
  NEXTAUTH_URL,
  NEXT_PUBLIC_TIME_OUT_MS,
  NEXT_PUBLIC_TIME_OUT_CHECK_MS,
  CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET,
};
